### PR TITLE
add article about fixing marionette memory leaks

### PR DESCRIPTION
**Pull request by sethjeffery**
@quipper/web-devs A new article! About leeks!

image

### CODE REVIEW

**Comment by tuttiq** [comment]
Is there any best-practice that suggests we should always prefer to set listeners on the views instead of the models or there's no such thing like that? It truly depends on your app's behavior and architecture, right?
Nice article!

**Comment by sethjeffery** [comment]
I had a look around and found no rule for whether listeners should or should not be on models. However the following is known:

- Backbone models have support for `listenTo` and `stopListening`, so they appear to approve of models and collections listening to other things.

- It is [preferred](http://stackoverflow.com/a/16824080/1228411) to use `listenTo` instead of `on` or `bind` because it makes it easier to track and release with `stopListening`.

**Comment by kyanny** [comment]
👍 Good to read. Shall I merge? @sethjeffery

**Comment by sethjeffery** [comment]
Please go ahead! :bow:

**Comment by kyanny** [comment]
:shipit:

**Comment by kyanny** [comment]
http://quipper.github.io/2016/04/08/fix-your-marionette-memory-leaks.html

**Pull request merged**
