### PR TITLE
Transplanting Across Branches

### PR DESCRIPTION
**Pull request by sethjeffery**
@quipper/developers a new article!

### CODE REVIEW

**Comment by masatomo** [comment]
:+1:

**Comment by masatomo** [comment]
I didn't know --onto well!

**Comment by kjcpaas** [comment]
I've always used `cherry-pick` but `--onto` seems a lot easier! No need to process each commit 1 by 1 :smile:

**Comment by bdesmero** [comment]
Thanks for this article @sethjeffery :dancer:

**Pull request merged**
