### PR TITLE
we agreed to let writers push straight to master

### PR DESCRIPTION
**Pull request by sethjeffery**
> kyanny [10:41 AM] 
But everyone feels it’s too much process,  I guess it’s ok to push your articleto  master branch directly (it’s more casual way)

### CODE REVIEW

**Comment by kyanny** [comment]
@sethjeffery 
I'd like to give other devs a chance to share their thoughs.
@quipper/developers How do you think about the publishing policy of our tech blog?

**Comment by banyan** [comment]
+1 for this publishing process.

**Comment by masatomo** [comment]
+1

**Comment by bdesmero** [comment]
:+1:

**Comment by anthonygood** [comment]
Personally, I'm against this. If we imagine the purpose of the blog is a showcase of talent, then I believe we should proofread against spelling and grammatical mistakes.

Spelling/grammar errors are quick and easy to fix, compared to the disproportionately negative impact they have on how a text is perceived.

Or so says I.

**Comment by sethjeffery** [comment]
@anthonygood What about the ability that we can issue PRs against each others' articles to fix their typos?

**Comment by rbmrclo** [comment]
:+1:

**Comment by anthonygood** [comment]
@sethjeffery That's a fine compromise, which I'd considered, though I have some reservations about it:
- Fixing other people's work can feel somewhat personal and invasive to the person whose work is under question
- PRs to retroactively fix bugs seems back-to-front, and I suspect will lead to errors remaining in texts

But, overall, if people promise to have a thick skin, it could be OK.

**Comment by sethjeffery** [comment]
@kyanny I think we're all agreed.

**Comment by kyanny** [comment]
:+1:

**Pull request merged**
